### ISSUE TITLE
[Bug] Role assignment logging

### ISSUE THREAD

**Issue by Liante-0216** [PaddoInWonderland/ValeOfMushrooms#2]
Hello,
I'm using Grenzpolizei V3 along with ZeLarpMaster's react_roles (found here https://github.com/ZeLarpMaster/ZeCogsV3) and Grenzpolizei seems to be having trouble registering the role assignment through reactions when they are "linked".

Here's the log:
https://hastebin.com/cexuyuwuro.sql

Steps to reproduce:
1. Install Grenzpolizei and react_roles
2. Run Grenzpolizei's autosetup
3. Set up some roles through reactions following react_roles built-in documentation
4. Link them using !roles link [channel.id-message.id]
5. Trigger some of the linked roles so that Red automatically removes the old one and assigns a new one

**Comment by PaddoInWonderland** [comment]
Hello, 

It should be resolved with push https://github.com/PaddoInWonderland/ValeOfMushrooms/commit/8429bd71301e0f0ae6c6771ea4f75136779a1b32
