### ISSUE TITLE
[Feature Request] Grenz optional output to file

### ISSUE THREAD

**Issue by mikeshardmind** [PaddoInWonderland/ValeOfMushrooms#3]
Title Mostly says it all, but I'd appreciate a file-based output for grenzpolizei if feasible as an optional alternative to a channel. If this isn't within scope, I completely understand.

**Comment by PaddoInWonderland** [comment]
As I believe, Grenzpolizei is already walking in a grey area of the Terms of Services of Discord on data collection of end users. I might have to contact them to get some clearance before I proceed the cog in a direction in which data is collected on a disk output.
