### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [PaddoInWonderland/ValeOfMushrooms#4]
grenzpolizei no longer works after the red update giving the error code:

RuntimeError: The Grenzpolizei cog in the grenzpolizei.grenzpolizei package does not inherit from the commands.Cog 
base class. The cog author must update the cog to adhere to this requirement.

**Comment by james-jimjam** [comment]
<img width="1027" alt="screenshot 2018-11-05 at 22 35 28" src="https://user-images.githubusercontent.com/6320434/48031218-5cc4d380-e14b-11e8-92ab-effd644256ff.png">
Currently using Dyno for logging in a couple of major servers and i dont like Dyno ;-) 

Let me know if you need any more help @PaddoInWonderland !

**Comment by Iangit1** [comment]
@james-jimjam This has been fixed. Please use the command `[p]cog update` to update your cogs to the latest working version.

**Comment by PaddoInWonderland** [comment]
Closed due to inactivity.
