### ISSUE TITLE
tickets closing / update not working

### ISSUE THREAD

**Issue by yikes101** [PaddoInWonderland/ValeOfMushrooms#8]
I am facing the issue that the tickets cog is closing / update functions isn't working. Bot simply deletes the issues command.

**Comment by yikes101** [comment]
@Iangit1 maybe you could look into that when you find a minute? As I have seen you did the latest commits and cog create left as fat as I know.

**Comment by yikes101** [comment]
Solved the issue myself.

**Comment by PaddoInWonderland** [comment]
Are willing to do a pull request @yikes101 ?

**Comment by yikes101** [comment]
It was more of a stupid mistake, I didnt add the generated "Ticket" role to myself.

I am wondering, was it planned that just users with the "Ticket" role are able to close a channel or also the user which created the channel? Because that is not working. Guess its some permission work. Looking into that now as I think also the ticket creator should be able to close it.

**Comment by yikes101** [comment]
> Are willing to do a pull request @yikes101 ?

It was more of a stupid mistake, I didnt add the generated "Ticket" role to myself.

I am wondering, was it planned that just users with the "Ticket" role are able to close a channel or also the user which opened the ticket? Because that is not working. Guess its some permission work. Looking into that now as I think also the ticket creator should be able to close it.
